CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    cpf        VARCHAR(255)                            NOT NULL,
    role        VARCHAR(50)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_cpf UNIQUE (cpf);
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);


CREATE TABLE portfolios
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance    DECIMAL(19, 2)                          NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_portfolios PRIMARY KEY (id)
);

ALTER TABLE portfolios ADD CONSTRAINT uc_portfolios_user UNIQUE (user_id);
ALTER TABLE portfolios ADD CONSTRAINT FK_PORTFOLIOS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


CREATE TABLE assets
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticker       VARCHAR(255)                            NOT NULL,
    company_name VARCHAR(255)                            NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_assets PRIMARY KEY (id)
);

ALTER TABLE assets ADD CONSTRAINT uc_assets_ticker UNIQUE (ticker);


CREATE TABLE positions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity       INTEGER                                 NOT NULL,
    average_price  DECIMAL(19, 2)                          NOT NULL,
    portfolio_id   BIGINT                                  NOT NULL,
    asset_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_positions PRIMARY KEY (id)
);

ALTER TABLE positions ADD CONSTRAINT uc_positions_portfolio_asset UNIQUE (portfolio_id, asset_id);
ALTER TABLE positions ADD CONSTRAINT FK_POSITIONS_ON_ASSET FOREIGN KEY (asset_id) REFERENCES assets (id);
ALTER TABLE positions ADD CONSTRAINT FK_POSITIONS_ON_PORTFOLIO FOREIGN KEY (portfolio_id) REFERENCES portfolios (id);


CREATE TABLE orders
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity          INTEGER                                 NOT NULL,
    price             DECIMAL(19, 2)                          NOT NULL,
    type              VARCHAR(255)                            NOT NULL,
    market_order_type VARCHAR(255)                            NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    portfolio_id      BIGINT                                  NOT NULL,
    asset_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders ADD CONSTRAINT FK_ORDERS_ON_ASSET FOREIGN KEY (asset_id) REFERENCES assets (id);
ALTER TABLE orders ADD CONSTRAINT FK_ORDERS_ON_PORTFOLIO FOREIGN KEY (portfolio_id) REFERENCES portfolios (id);


CREATE TABLE transactions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity     INTEGER                                 NOT NULL,
    price        DECIMAL(19, 2)                          NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    timestamp    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    portfolio_id BIGINT                                  NOT NULL,
    asset_id     BIGINT                                  NOT NULL,
    order_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

ALTER TABLE transactions ADD CONSTRAINT uc_transactions_order UNIQUE (order_id);
ALTER TABLE transactions ADD CONSTRAINT FK_TRANSACTIONS_ON_ASSET FOREIGN KEY (asset_id) REFERENCES assets (id);
ALTER TABLE transactions ADD CONSTRAINT FK_TRANSACTIONS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE transactions ADD CONSTRAINT FK_TRANSACTIONS_ON_PORTFOLIO FOREIGN KEY (portfolio_id) REFERENCES portfolios (id);