INSERT INTO assets (ticker, company_name, type) VALUES ('BBAS3', 'Banco do Brasil S.A', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('PETR4', 'Petrobrás PN', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('VALE3', 'Vale S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('ITUB4', 'Itaú Unibanco Holding S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('BBDC4', 'Banco Bradesco S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('ABEV3', 'Ambev S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('MGLU3', 'Magazine Luiza S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('WEGE3', 'WEG S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('B3SA3', 'B3 S.A. - Brasil, Bolsa, Balcão', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('SUZB3', 'Suzano S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('GGBR4', 'Gerdau S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('RENT3', 'Localiza Rent a Car S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('LREN3', 'Lojas Renner S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('VVAR3', 'Via S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('ELET3', 'Eletrobras', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('ITSA4', 'Itaúsa S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('JBSS3', 'JBS S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('RADL3', 'Raia Drogasil S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('UGPA3', 'Ultrapar Participações S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('HAPV3', 'Hapvida Participações e Investimentos S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('EMBR3', 'Embraer S.A.', 'STOCK');
INSERT INTO assets (ticker, company_name, type) VALUES ('AZUL4', 'Azul S.A.', 'STOCK');
