-- Inserindo 10 Ações Brasileiras
INSERT INTO assets (ticker, company_name, type) VALUES
    ('PETR4', 'Petrobras', 'STOCK'),
    ('VALE3', 'Vale', 'STOCK'),
    ('ITUB4', 'Itaú Unibanco', 'STOCK'),
    ('BBAS3', 'Banco do Brasil', 'STOCK'),
    ('BBDC4', 'Bradesco', 'STOCK'),
    ('B3SA3', 'B3 - Brasil Bolsa Balcão', 'STOCK'),
    ('ELET3', 'Eletrobras', 'STOCK'),
    ('ABEV3', 'Ambev', 'STOCK'),
    ('WEGE3', 'WEG', 'STOCK'),
    ('SUZB3', 'Suzano', 'STOCK'),
    ('GGBR4', 'Gerdau', 'STOCK'),
    ('MGLU3', 'Magazine Luiza', 'STOCK'),
    ('LREN3', 'Lojas Renner', 'STOCK'),
    ('RADL3', 'Raia Drogasil', 'STOCK'),
    ('PRIO3', 'Prio (PetroRio)', 'STOCK'),
    ('RENT3', 'Localiza', 'STOCK'),
    ('VBBR3', 'Vibra Energia', 'STOCK'),
    ('CSNA3', 'CSN', 'STOCK'),
    ('UGPA3', 'Ultrapar', 'STOCK'),
    ('BRFS3', 'BRF', 'STOCK'),
    ('EQTL3', 'Equatorial Energia', 'STOCK'),
    ('EMBR3', 'Embraer', 'STOCK'),
    ('KLBN11', 'Klabin', 'STOCK'),
    ('BPAC11', 'BTG Pactual', 'STOCK');