-- Inserindo 10 Ações Brasileiras
INSERT INTO assets (ticker, company_name, type) VALUES
    ('PETR4', 'Petrobras', 'STOCK'),
    ('VALE3', 'Vale', 'STOCK'),
    ('ITUB4', 'Itaú Unibanco', 'STOCK'),
    ('BBAS3', 'Banco do Brasil', 'STOCK'),
    ('BBDC4', 'Bradesco', 'STOCK'),
    ('B3SA3', 'B3 - Brasil Bolsa Balcão', 'STOCK'),
    ('ELET3', 'Eletrobras', 'STOCK'),
    ('ABEV3', 'Ambev', 'STOCK'),
    ('WEGE3', 'WEG', 'STOCK'),
    ('SUZB3', 'Suzano', 'STOCK'),
    ('GGBR4', 'Gerdau', 'STOCK'),
    ('MGLU3', 'Magazine Luiza', 'STOCK'),
    ('LREN3', 'Lojas Renner', 'STOCK'),
    ('RADL3', 'Raia Drogasil', 'STOCK'),
    ('PRIO3', 'Prio (PetroRio)', 'STOCK'),
    ('RENT3', 'Localiza', 'STOCK'),
    ('VBBR3', 'Vibra Energia', 'STOCK'),
    ('CSNA3', 'CSN', 'STOCK'),
    ('UGPA3', 'Ultrapar', 'STOCK'),
    ('JBSS3', 'JBS', 'STOCK'),
    ('BRFS3', 'BRF', 'STOCK'),
    ('EQTL3', 'Equatorial Energia', 'STOCK'),
    ('EMBR3', 'Embraer', 'STOCK'),
    ('KLBN11', 'Klabin', 'STOCK'),
    ('BPAC11', 'BTG Pactual', 'STOCK'),

-- Inserindo 25 Fundos Imobiliários (FII)
    ('MXRF11', 'Maxi Renda FII', 'FII'),
    ('HGLG11', 'CSHG Logística', 'FII'),
    ('BTLG11', 'BTG Pactual Logística', 'FII'),
    ('XPML11', 'XP Malls', 'FII'),
    ('KNCR11', 'Kinea Renda Imobiliária', 'FII'),
    ('CPTS11', 'Capitânia Investimentos', 'FII'),
    ('VISC11', 'Vinci Shopping Centers', 'FII'),
    ('HGRU11', 'CSHG Renda Urbana', 'FII'),
    ('IRDM11', 'Iridium Recebíveis', 'FII'),
    ('RECR11', 'REC Recebíveis', 'FII'),
    ('BCFF11', 'BTG Pactual Fundo de Fundos', 'FII'),
    ('VILG11', 'Vinci Logística', 'FII'),
    ('XPLG11', 'XP Log', 'FII'),
    ('GGRC11', 'GGR Copevi Renda', 'FII'),
    ('VRTA11', 'Votorantim Renda', 'FII'),
    ('RZTR11', 'Riza Terrax', 'FII'),
    ('MCCI11', 'Mauá Capital Recebíveis', 'FII'),
    ('BRCO11', 'Bresco Logística', 'FII'),
    ('KNIP11', 'Kinea Índice de Preços', 'FII'),
    ('HFOF11', 'Hedge Top FOF', 'FII'),
    ('VINO11', 'Vinci Ofs FII', 'FII'),
    ('KNSC11', 'Kinea Securities', 'FII'),
    ('PVBI11', 'VBI Prime Properties', 'FII'),
    ('RBRP11', 'RBR Propriedades', 'FII'),
    ('AFHI11', 'AF Invest CRI', 'FII');

